### ISSUE TITLE
Separate flat files cms and static site generators

### ISSUE THREAD

**Issue by LomigLavnek** [bevry/staticsitegenerators-list#220]
I think these two categories are very different and it would be good to separate them.

A flat system cms has no sql database, but it doesn't mean there's only one file modified per post, or that it is easily human-writable. I know one (pluxml) and files are in xml, so don't think you can easily write it and upload on the server, it's just a mess to do. It has to be managed with administation system for efficients result. Their use are closer cms use than static generator.

A new key could be introduce in list.yaml such as type : "flat" or type: "static"

**Comment by davisonio** [comment]
Yep, I agree that they are very different. Categories are a good idea or maybe we should not even including them on this list at all? I don't consider flat file CMSs static site generators.

Thoughts @bevry/ssg-listing-team?

**Comment by balupton** [comment]
Could be an extension of https://github.com/bevry/staticsitegenerators-list/issues/7

I've been thinking of this for a while now, my thoughts lead me to suggest that we should introduce a few new columns/fields/flags for particular features, mostly to correspond with the feature categories as already denoted in our README, as well as to better warrant what potential users would be looking for in particular solutions and to differentiate between entries in our current listing.

For instance, we've bundled static hosting services (like BitBalloon) and other types all under a "Commercial" license, as well as discarding or misplacing static content editing solutions (like Prose), both of which are still related to the SSG scene, and useful to SSG consumers, albeit not being SSGs themselves.

As what really is the point of the listing? To be a useful resource of all projects that are SSG related in my mind. Why such a broad definition? Because simply a listing of a strict SSG only listing would not be as useful for one looking for strict SSGs, as one that includes broader projects in the SSG scene. I'd also imagine that most people to the listing are newcomers to the SSG scene, and knowing the differences in features as we already do, would be a informative and helpful experience for them to make better decisions. For instance, perhaps they don't know you can hook Flat-File CMS SSGs  up to Prose to get a Editing Interface as well, opting for a SSG that bundles a editing interface inside it.

As such, here is a proposal.

We introduce these fields as boolean flags, that are features on the website as columns which entries that support them have checkmarks in the columns:

1. Outputs Static Website (in the README how we define a SSG)
2. Static Server (provides a server for displaying static/rendered content)
3. Dynamic Server (provides a server that can render content on-the-fly)
4. Extendable Server (provides a server that can be extended with your own routing)
5. Inputs Static Files (in the README defined as Flat-File CMS)
6. Inputs Dynamic Content (provides the ability to import content from external databases and APIs)
7. Hosting Solution (provides a hosting solution for your static-orientated website)
8. GUI Editor (provides a editing interface as accustomed to in the traditional CMS/WYSIWYG apps)

Inside the YAML file, each of these will be a boolean field. Inside the website, they will each be a column that if true will have a checkmark inside. On the website, users can then sort the entries by the feature columns they care about, as well as serving to inform them on the different features available in the SSG scene.

**Comment by davisonio** [comment]
I think this proposal is a great one and will hopefully help people to find the static site generator suitable for their needs.

> For instance, we've bundled static hosting services (like BitBalloon) and other types all under a "Commercial" license, as well as discarding or misplacing static content editing solutions (like Prose), both of which are still related to the SSG scene, and useful to SSG consumers, albeit not being SSGs themselves.

Yes, this also creates a problem when the software is both offered as an open source project but also as a commercial platform - which option do they go under?

> I'd also imagine that most people to the listing are newcomers to the SSG scene, and knowing the differences in features as we already do, would be a informative and helpful experience for them to make better decisions.

Perhaps we should add some reference to the [gostatic](https://github.com/bevry/gostatic) campaign on the website? At the moment a new user wouldn't  know why they should be using one of the many static site generators on this website over something like Wordpress or even Wordpress.com.

The only problem I see with your proposal is that it would be quite hard to consider which projects would be "related to the SSG scene". It's definitely open to much interpretation - what's useful for one person may not be useful for the other.

We might also need some checking to make sure that all projects listed include the correct categories/tags. For example, make sure that there is a feature explaining where the input is from (plain file, database, API etc.).

One suggestion I have is to clearly show the `Input:` and `Output:`. Let's say that I have a collection of static markdown files - I could then order the list by `Input: Static Files` and see what options there are for me. In summary three main categories: input (e.g. Input: Static Files), output (e.g. Output: Static Website) and feature (e.g. Feature: GUI Editor).

**Comment by LomigLavnek** [comment]
As we discuss about classification, wouldn't it be good to create a category about generator usage like:
- portal
- blog
- wiki
- image gallery ?

**Comment by balupton** [comment]
@LomigLavnek I'd imagine most of them could be used for anything/all, could become an endless update battle

**Comment by balupton** [comment]
> Perhaps we should add some reference to the gostatic campaign on the website? At the moment a new user wouldn't know why they should be using one of the many static site generators on this website over something like Wordpress or even Wordpress.com.

+1, although I'd imagine bevry/gostatic will need some updates - but perhaps doing that link will give it the attention and consequently the updates it needs

**Comment by balupton** [comment]
@davisonio regarding your queries, it's interesting, and I've revised the text following several times.

I'd imagine a change of:

```
- name: "DocPad"
  github: "docpad/docpad"
  license: "MIT"
  website: "http://docpad.org"
  language: "CoffeeScript"
```

To something like:

``` yams
- name: "DocPad"
  github: "docpad/docpad"
  license: "MIT"
  website: "http://docpad.org"
  language: "CoffeeScript"
  supports:
    - "Static Input"  # can input static files via core or plugins
    - "Static Output"  # can output static files via core or plugins
    - "Dynamic Input"  # can input dynamic content via core or plugins
    - "Dynamic Output"  # can output dynamic content via core or plugins (re-rendering, server extensions)
    - "Static Server"  # will work entirely with a static server via core or plugins
    - "Dynamic Server"  # will work entirely with a dynamic server via core or plugins
    - "Extendable Server"  # server can be extended directly via plugins or API
    - "Extendable Rendering"  # rendering can be extended directly via plugins or API
    - "API System"  # core can be used via programmable API (not just a command line interface)
    - "Plugin System"  # core can be extended via plugins
```

This is more or less suitable. However unsuitable for also bundling things like Prose, BitBalloon, Surge.sh, and other not SSG ("Static Output" feature) or Flat-File CMS ("Static Input") solutions. So I'm thinking what we should do is actually have two listings.

`list.yaml` for entries that either have "Static Output" or "Static Input", then additionally we also have a `resources.yaml` for entries that are neither "Static Output" or "Static Input" however area released to one or the other, such as Prose, BitBallon, Surge.sh, or perhaps even bevry/gotstatic and https://www.staticgen.com which have an "is" field that is either "Hosting" (surge, BitBalloon), "Editing" (Prose), "Information" (StaticGen, GoStatic).

I'm also thinking we can update the website to allow comments or reviews or ratings or entries.

**Comment by balupton** [comment]
I can imagine we could add many different features to that listing, however I'd say those are all the main and most important ones. "Internationalisation" is probably up there, however from my awareness this is usually added on-top of SSGs that may or may not have direct core or plugin support for them, more of a user land thing, so would be hard to define strict criteria for unlike the other features...

**Comment by davisonio** [comment]
This is a nice idea and I have been thinking about the proposal. I'd say it would be best not to include many tags as it would require a lot of frequent updating because projects change their scope regularly and remove or add features regularly too.

The resources idea sounds okay too, as long as it's clearly distinguishable from the actual list and looks mostly different. Here we could link to relevant resources for the static site generator community.

**Comment by balupton** [comment]
Cool. Let's lock in the resources listing.

What tags would you have and which would you get rid of?

One of my thoughts is that if done well enough, and with the notion of reviews/comments on static site generators inside the listing, and with the addition of the resources listing, and perhaps a merging of https://github.com/bevry/goopen - the website could progress into the not just the definitive listing, but the definitive resource on static site generator stuff, in which case SSG authors and community members would want to keep their items listing up to date, as it would be a major discovery and traffic source for them and their users, as well as the SSG movement and scene in general

**Comment by balupton** [comment]
I'd imagine with the addition of reviews, each entry would get their own page that can be loaded via URL or if a modal via a hash, with the listing only providing a star rating, that when clicked will show the modal or redirect to the page to see the full entry with the reviews below and ratings on several different areas.

**Comment by davisonio** [comment]
I think that the first ones we could start off with should be Static Input, Static Output, Dynamic Input, Dynamic Output and maybe a few others.

:+1: on the definitive static site generator resource idea!

Yes, adding a review page would be great idea for traffic and displaying a short description of the static site generator / resource.

**Comment by balupton** [comment]
Cool, sounds like we have enough conformity to move ahead with this!

@jaspervdj any feedback?

**Comment by balupton** [comment]
Okay spent the afternoon on this, and came up with the following:

---

- `is` should be one of the following:
  - `file file cms` a project that takes in local file content, renders it, and exposes the rendered contents via its own web server, without exporting to static files that can be deployment elsewhere, such as Grav and Harp
  - `static site generator` a project that takes in local file content, renders it, and exports it into a static file content for deployment somewhere, with or without a bundled web server, such as Jekyll and DocPad
  - `static site importer` a project that takes in local or dynamic content and imports it into a database, such as a file system to Contentful importer
  - `static site exporter` a project that takes in database content and generates a static website with it, such as a Contentful or Wordpress to static website exporter
  - `static site deployment` a project that hosts static site content, such as GitHub Pages or Surge.sh
  - `static site editor` a project that a custom editing experience for static website content, such as Contentful and Prose.io, or even Grav's admin plugin
  - `other` if some other type of project that is related to flat-file content management systems or static website generators
- `extensible` should be `true` or `false` providing whether or not the project provides a way for users to add new features

---

Seems good. If there are more types that develop from other, we can add another `is` field when they become notable.

**Comment by dertuxmalwieder** [comment]
Shouldn't this be reflected in the UI?

**Comment by balupton** [comment]
@dertuxmalwieder yep, it is only recent that these changes were made, the UI will get some major overhauls by the end of the year :-)

**Comment by dertuxmalwieder** [comment]
Great, thanks!

**Comment by balupton** [comment]
@dertuxmalwieder invite sent
