### ISSUE TITLE
Bug: Bitbucket entries not listed

### ISSUE THREAD

**Issue by dertuxmalwieder** [bevry/staticsitegenerators-list#281]
As of now, there is exactly one entry (Latemp) in the list that has a `bitbucket` field (as described in the README).

But this entry does not appear on the website.

Obviously, there seems to be a bug.

**Comment by balupton** [comment]
Could be a caching issue. If so, #19 will probably fix this. Will be on my list for end of next week.

**Comment by balupton** [comment]
yep, was caching issue, as it is now showing on website

**Comment by dertuxmalwieder** [comment]
Actually, it's not. My blogc++ entry still links to the website without a Bitbucket symbol.

**Comment by balupton** [comment]
@dertuxmalwieder seems confused with https://github.com/bevry/staticsitegenerators-list/issues/40 (adding bitbucket enhancements)

this issue was about a bitbucket entry not showing at all on the website - which was due to caching - as it is now showing - `Latemp`

<img width="1440" alt="screen shot 2017-02-23 at 7 14 29 am" src="https://cloud.githubusercontent.com/assets/61148/23237339/d0d52f88-f997-11e6-84be-23b06d1b95f6.png">

**Comment by dertuxmalwieder** [comment]
In this case, my bug report actually reported the wrong bug. ;-)
Thanks though.

**Comment by balupton** [comment]
cool, shall we close this one?

**Comment by dertuxmalwieder** [comment]
*shrug*
